//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MedicalNotes_Doctor
    {
        public int ID_записи { get; set; }
        public System.DateTime Дата_время { get; set; }
        public string Содержание { get; set; }
        public int ID_пациента { get; set; }
        public int ID_врача { get; set; }
    }
}
