//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Prescriptions_Doctor
    {
        public int ID_назначения { get; set; }
        public string Лекарство { get; set; }
        public string Дозировка { get; set; }
        public string Период_приёма { get; set; }
        public int Статус { get; set; }
        public Nullable<int> ID_приёма { get; set; }
        public int ID_пациента { get; set; }
        public int ID_врача { get; set; }
    }
}
