//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Appointments_Doctor
    {
        public int ID_приёма { get; set; }
        public System.DateTime Дата_время { get; set; }
        public int Статус { get; set; }
        public string Жалобы { get; set; }
        public string Примечание_врача { get; set; }
        public int ID_пациента { get; set; }
        public int ID_врача { get; set; }
        public int ID_кабинета { get; set; }
        public string Код_диагноза { get; set; }
        public Nullable<int> ID_направления { get; set; }
    }
}
