//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Амбулаторная_карта
    {
        public int ID_карты { get; set; }
        public string Группа_крови { get; set; }
        public string Аллергии { get; set; }
        public string Вредные_привычки { get; set; }
        public string Доп_информация { get; set; }
        public int ID_пациента { get; set; }
    
        public virtual Пациенты Пациенты { get; set; }
    }
}
