//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Журнал_аудита
    {
        public long ID_записи { get; set; }
        public int ID_пользователя { get; set; }
        public string Таблица { get; set; }
        public string Операция { get; set; }
        public string ID_записи_в_таблице { get; set; }
        public string Старое_значение { get; set; }
        public string Новое_значение { get; set; }
        public string IP_адрес { get; set; }
        public System.DateTime Дата_время { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
