//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Лабораторные_исследования
    {
        public int ID_исследования { get; set; }
        public string Тип_анализа { get; set; }
        public System.DateTime Дата_назначения { get; set; }
        public Nullable<System.DateTime> Дата_выполнения { get; set; }
        public string Результат { get; set; }
        public int Статус { get; set; }
        public Nullable<int> ID_приёма { get; set; }
        public int ID_пациента { get; set; }
        public int ID_врача { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Пациенты Пациенты { get; set; }
        public virtual Приёмы Приёмы { get; set; }
    }
}
