//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Направления
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Направления()
        {
            this.Приёмы = new HashSet<Приёмы>();
        }
    
        public int ID_направления { get; set; }
        public string Номер { get; set; }
        public System.DateTime Дата_выдачи { get; set; }
        public System.DateTime Срок_действия { get; set; }
        public string Цель { get; set; }
        public int Статус { get; set; }
        public int ID_пациента { get; set; }
        public int ID_врача_направившего { get; set; }
        public int ID_врача_к_которому { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Врачи Врачи1 { get; set; }
        public virtual Пациенты Пациенты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Приёмы> Приёмы { get; set; }
    }
}
