//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Пользователи()
        {
            this.Журнал_аудита = new HashSet<Журнал_аудита>();
        }
    
        public int ID_пользователя { get; set; }
        public string Логин { get; set; }
        public string Хеш_пароля { get; set; }
        public int Роль { get; set; }
        public Nullable<int> ID_врача { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Журнал_аудита> Журнал_аудита { get; set; }
        public virtual Роли Роли { get; set; }
    }
}
