//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Приёмы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Приёмы()
        {
            this.Лабораторные_исследования = new HashSet<Лабораторные_исследования>();
            this.Лекарственные_назначения = new HashSet<Лекарственные_назначения>();
        }
    
        public int ID_приёма { get; set; }
        public System.DateTime Дата_время { get; set; }
        public int Статус { get; set; }
        public string Жалобы { get; set; }
        public string Примечание_врача { get; set; }
        public int ID_пациента { get; set; }
        public int ID_врача { get; set; }
        public int ID_кабинета { get; set; }
        public string Код_диагноза { get; set; }
        public Nullable<int> ID_направления { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Диагнозы_МКБ10 Диагнозы_МКБ10 { get; set; }
        public virtual Кабинеты Кабинеты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Лабораторные_исследования> Лабораторные_исследования { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Лекарственные_назначения> Лекарственные_назначения { get; set; }
        public virtual Направления Направления { get; set; }
        public virtual Пациенты Пациенты { get; set; }
    }
}
