//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyclinicApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Расписание
    {
        public int ID_расписания { get; set; }
        public int День_недели { get; set; }
        public System.TimeSpan Время_начала { get; set; }
        public System.TimeSpan Время_окончания { get; set; }
        public bool Активно { get; set; }
        public int ID_врача { get; set; }
        public int ID_кабинета { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Кабинеты Кабинеты { get; set; }
    }
}
